spring.application.name=agrosatalert

# Configuracao do perfil ativo
spring.profiles.active=test

# Porta do servidor
server.port=8080

# Configuracao JPA
spring.jpa.show-sql=true
spring.jpa.format-sql=true